### PR TITLE
fix: improve logging for connection manager

### LINKED ISSUE #1270: Connection Manager: print dialing errors
This is a **bug report/feature or change request/support request**

## Problem

Connection manager does not give much information about error encountered:

```
09:47:06.495 waku:connection-manager Connection Manager is now running +0ms index.js:29160:10
09:47:06.505 waku:connection-manager Dialing peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e +10ms index.js:29160:10
09:47:06.511 waku:connection-manager 
          Error dialing peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e +7ms index.js:29160:10
09:47:06.511 waku:connection-manager Reattempting dial (1) +0ms index.js:29160:10
09:47:06.512 waku:connection-manager Dialing peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e +0ms index.js:29160:10
09:47:06.516 waku:connection-manager 
          Error dialing peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e +4ms index.js:29160:10
09:47:06.516 waku:connection-manager Reattempting dial (2) +1ms index.js:29160:10
09:47:06.517 waku:connection-manager Dialing peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e +0ms index.js:29160:10
09:47:06.520 waku:connection-manager 
          Error dialing peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e +3ms index.js:29160:10
09:47:06.520 waku:connection-manager Reattempting dial (3) +1ms index.js:29160:10
09:47:06.520 waku:connection-manager Dialing peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e +0ms index.js:29160:10
09:47:06.522 waku:connection-manager 
          Error dialing peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e +2ms index.js:29160:10
09:47:06.523 waku:connection-manager Deleting undialable peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e from peer store +0ms
```

Enabling libp2p logs does not help much:

```
13:31:57.381 waku:connection-manager 
          Error dialing peer 16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD +6ms [index.js:29160:10](https://unpkg.com/@waku/create@0.0.9/bundle/index.js)
13:31:57.381 waku:connection-manager Reattempting dial (1) +0ms [index.js:29160:10](https://unpkg.com/@waku/create@0.0.9/bundle/index.js)
13:31:57.381 waku:connection-manager Dialing peer 16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD +0ms [index.js:29160:10](https://unpkg.com/@waku/create@0.0.9/bundle/index.js)
13:31:57.384 libp2p:connection-manager dial to +9ms 
Object { type: "secp256k1", multihash: {…}, privateKey: undefined, publicKey: Uint8Array(37), … }
[index.js:29160:10](https://unpkg.com/@waku/create@0.0.9/bundle/index.js)
13:31:57.384 libp2p:dialer creating dial target for 16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD +9ms [index.js:29160:10](https://unpkg.com/@waku/create@0.0.9/bundle/index.js)
13:31:57.384 libp2p:peer-store:address-book:trace get wait for read lock +7ms [index.js:29160:10](https://unpkg.com/@waku/create@0.0.9/bundle/index.js)
13:31:57.385 libp2p:peer-store:trace getPeers release read lock +13ms [index.js:29160:10](https://unpkg.com/@waku/create@0.0.9/bundle/index.js)
13:31:57.385 libp2p:peer-store:trace getPeers release read lock +0ms 2 [index.js:29160:10](https://unpkg.com/@waku/create@0.0.9/bundle/index.js)
13:31:57.385 libp2p:peer-store:address-book:trace get got read lock +1ms [index.js:29160:10](https://unpkg.com/@waku/create@0.0.9/bundle/index.js)
13:31:57.386 libp2p:peer-store:address-book:trace get release read lock +0ms
```

Also note `toString` could be used on the peerid for this line:

```
13:31:57.384 libp2p:connection-manager dial to +9ms 
Object { type: "secp256k1", multihash: {…}, privateKey: undefined, publicKey: Uint8Array(37), … }
```

## Proposed Solutions

- Log the error encountered when dialing
- Stringify objects in logs when appropriate

### PR DESCRIPTION
**Pull request by danisharora099**
## Problem

#1270 

## Solution

Add verbosity to the error message on why the dial request failed

Example when the multiaddr isn't online: 

```  waku:connection-manager Error dialing peer 16Uiu2HAm82ASpFj7QhGSo69Gjv8ahkJQyNVPoepTNQdop1Nzvpx8 - Error: connect ECONNREFUSED 127.0.0.1:12303```

## Notes

- Closes #1270

### CODE REVIEW

File: packages/core/src/lib/connection_manager.ts [hunk 1]
```diff
@@ -115,7 +117,12 @@ export class ConnectionManager {
     }
 
     try {
-      log(`Deleting undialable peer ${peerId.toString()} from peer store`);
+      log(
+        `Deleting undialable peer ${peerId.toString()} from peer store. Error: ${JSON.stringify(
```
Comment (weboko) [inline packages/core/src/lib/connection_manager.ts:121]: I would advice to change `lastErrorRecorder` to a map where we have `peerId` - `error` relationship.
Need to make sure to clean it once it is not needed not to increase memory consumption (for now not issue but later it could become one).

File: packages/core/src/lib/connection_manager.ts [hunk 2]
```diff
@@ -102,9 +103,10 @@ export class ConnectionManager {
 
         this.dialAttemptsForPeer.delete(peerId.toString());
         return;
-      } catch (error) {
-        log(`
-          Error dialing peer ${peerId.toString()}`);
+      } catch (error: any) {
+        lastErrorRecorded = error;
+        log(`Error dialing peer ${peerId.toString()} - ${error.errors}`);
```
Comment (weboko) [inline packages/core/src/lib/connection_manager.ts:108]: `any` have no guarantees for `.errors` to be in place.
Let's use `.?` here and/or maybe add proper type.

Comment (fryorcraken) [reply packages/core/src/lib/connection_manager.ts:108]: `catch` does not need typing. I believe the type is TypeScript in-built type `Error`.

Also, I would go against string manipulating errors, just let `debug` handle it:

```
log(`Error dialing peer ${peerId.toString()}`, error);
```

File: packages/core/src/lib/connection_manager.ts (hunk 1 above)
Comment (fryorcraken) [reply packages/core/src/lib/connection_manager.ts:121]: Agree with comment above. I think it can be cleaned as soon as used.

Is this necessary? If a dev see the errors for this peer id in the logs and then see that it's deleted I think they can correlate easily, especially that peer id is present.

Also, do not JSON/string manipulate errors:
 log( `Deleting undialable peer ${peerId.toString()} from peer store`, lastErrorRecorded)

**Review by fryorcraken — CHANGES_REQUESTED** [review]
I'd rather not introduce `any` when not strictly necessary. See comments.

Also, not convinced the `lastError` is needed.

File: packages/core/src/lib/connection_manager.ts [hunk 3]
```diff
@@ -102,9 +103,10 @@ export class ConnectionManager {
 
         this.dialAttemptsForPeer.delete(peerId.toString());
         return;
-      } catch (error) {
-        log(`
-          Error dialing peer ${peerId.toString()}`);
+      } catch (error: any) {
```
Comment (fryorcraken) [inline packages/core/src/lib/connection_manager.ts:106]: Can you cast the type to `Error` (I think that's the right one) instead?
ie,
```
const e = error as unknown as Error;
```

So that the right type can also be used in the `Map`?

File: packages/core/src/lib/connection_manager.ts (hunk 1 above)
Comment (weboko) [reply packages/core/src/lib/connection_manager.ts:121]: As I see we do only `stringify` on the error, then to me it makes sense to have `Map<peerId, string>`.
Another improvement I would advice is to identify what we need to log from the error - maybe only message property? The reason is that `stringify` can throw if the object has circular dependencies and since we do not own `libp2p` it might be anything.

File: packages/core/src/lib/connection_manager.ts (hunk 3 above)
Comment (fryorcraken) [reply packages/core/src/lib/connection_manager.ts:106]: Sounds good to upgrade yes. re es2021 vs es2022 let's look at browser support and make a reasonable decision. Cc @weboko who might be more acquainted with those.

**Review by fryorcraken — APPROVED** [review]
